make it harder to deploy with out someones approval

diff --git a/infrastructure/Taskfile.yml b/infrastructure/Taskfile.yml
--- a/infrastructure/Taskfile.yml
+++ b/infrastructure/Taskfile.yml
@@ -897,6 +897,26 @@ tasks:
           fi
       preconditions:
       - *require_site
+      - &require_clean_state {
+          sh: "[
+            current_branch=$(git branch --show-current)
+            if [ 'current_branch' != 'main' ]; then
+              echo 'Can't deploy if not on main branch'
+              exit 1
+            fi
+            if ! git diff-index --quiet HEAD --; then
+              echo 'Can't deploy if there's changes on the branch'
+              exit 1
+            fi
+            exit 0 #
+          ]",
+          msg: "############################################################ \n
+                \n
+                It's not possible to deploy from other branches than main.\n
+                Furthermore your state has to be clean \n
+                \n
+                ############################################################"
+        }
 
     site:autoscaler:
       desc: Runs the a dpladm setup of horizontal autoscaler, making sure the site has an autoscaler configured
